In [90]:
import pandas as pd
import numpy as np

In [91]:
true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

In [92]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [93]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [94]:
true['label']=1

In [95]:
fake['label']=0

In [96]:
news = pd.concat([fake,true], axis=0)

In [97]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [98]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [99]:
news = news.drop(['title','date'],axis = 1)

In [100]:
news.head()

                                                text subject  label
0  Donald Trump just couldn t wish all Americans ...    News      0
1  House Intelligence Committee Chairman Devin Nu...    News      0
2  On Friday, it was revealed that former Milwauk...    News      0
3  On Christmas day, Donald Trump announced that ...    News      0
4  Pope Francis used his annual Christmas Day mes...    News      0

In [101]:
news = news.sample(frac=1) #reshuffling

In [102]:
news.head()

                                                    text    subject  label
19302  As the Pussyhat Project s flier helpfully poin...  left-news      0
12165  Wikileaks founder Julian Assange has clearly s...   politics      0
13250  Wow! This compilation of blatant blocking for ...   politics      0
20801  This video is so disturbing but is a great exa...  left-news      0
21334  VATICAN CITY (Reuters) - It is perhaps  only a...  worldnews      1

In [103]:
news = news.reset_index(inplace=True)

In [109]:
news.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [111]:
news = pd.concat([fake,true], axis=0)
news = news.drop(['title','date'],axis = 1)
news = news.sample(frac=1)
news = news.reset_index(drop=True)

In [112]:
news.reset_index(inplace=True)

In [113]:
news.head()

   index                                               text    subject  label
0      0  ISLAMABAD (Reuters) - Pakistan s electoral com...  worldnews      1
1      1  Just recently, a USA Today sports columnist sa...   politics      0
2      2  Vince Foster Part II?The death by barbell of d...   politics      0
3      3  WASHINGTON (Reuters) - The North Korean foreig...  worldnews      1
4      4  BERLIN (Reuters) - German Foreign Minister Sig...  worldnews      1

In [1]:
news.drop(['index'],axis=1,inplace=True)

NameError: name 'news' is not defined

In [115]:
news.head()

                                                text    subject  label
0  ISLAMABAD (Reuters) - Pakistan s electoral com...  worldnews      1
1  Just recently, a USA Today sports columnist sa...   politics      0
2  Vince Foster Part II?The death by barbell of d...   politics      0
3  WASHINGTON (Reuters) - The North Korean foreig...  worldnews      1
4  BERLIN (Reuters) - German Foreign Minister Sig...  worldnews      1

In [117]:
import re

In [118]:
def wordopt(text):
    #Convert into lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+','',text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Remove digits
    text = re.sub(r'\d', '', text)

    # Remove newline characters
    text = re.sub(r'\n', ' ', text)

    return text

In [119]:
news['text'] = news['text'].apply(wordopt)

In [120]:
news['text']

0        islamabad reuters  pakistan s electoral commis...
1        just recently a usa today sports columnist sai...
2        vince foster part iithe death by barbell of di...
3        washington reuters  the north korean foreign m...
4        berlin reuters  german foreign minister sigmar...
                               ...
44893    it sure would be nice to have a president and ...
44894    the protesters are breaking all the rules and ...
44895    chicago reuters  illinois governor on wednesda...
44896    just a few days ago presidentelect donald trum...
44897    donald trump s first debate against his democr...
Name: text, Length: 44898, dtype: object

In [121]:
x = news['text']
y = news['label']

In [ ]:
x

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
x_train.shape

In [ ]:
x_test.shape

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorization = TfidfVectorizer()

In [ ]:
xv_train = vectorization.fit_transform(x_train)

In [ ]:
xv_test = vectorization.transform(x_test)

In [ ]:
xv_train

In [ ]:
xv_test

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
LR = LogisticRegression()

In [ ]:
LR.fit(xv_train,y_train)

In [ ]:
pred_lr = LR.predict(xv_test)

In [ ]:
LR.score(xv_test,y_test)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr))

In [ ]:



from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier()

In [ ]:
DTC.fit(xv_train , y_train)

In [ ]:
pred_dtc = DTC.predict(xv_test)

In [ ]:
DTC.score(xv_test,y_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

print(classification_report(y_test, pred_dtc))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier()

In [ ]:
rfc.fit(xv_train , y_train)

In [ ]:
predict_rfc  = rfc.predict(xv_test)

In [ ]:
rfc.score(xv_test,y_test)

In [ ]:
print(classification_report(y_test, predict_rfc)  )

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gbc = GradientBoostingClassifier()

In [ ]:
gbc.fit(xv_train , y_train)

In [ ]:
print(classification_report(y_test, predict_rfc))

In [ ]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Real News"
    else:
        return "Unknown"

In [ ]:
def manual_testing(news):
    testing_news = {"text": [news]} # Corrected syntax for defining dictionary
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)  # Assuming 'vectorization' is your vectori
    pred_lr = LR.predict(new_xv_test)
    # pred_dtc = dtc.predict(new_xv_test)
    pred_gbc = gbc.predict(new_xv_test)
    pred_rfc = rfc.predict(new_xv_test)
    return "\n\nLR Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(
        output_label(pred_lr[0]), output_label(pred_gbc[0]), output_label(pred_rfc[0]))

In [ ]:
news_article = str(input())

In [ ]:
manual_testing(news_article)